{% extends "base.phtml" %}


{% block title %}Fuzzwork Market Data{% endblock %}

{% block content %}
<div class="content">
<div class="pure-g">
<div class="pure-u-1">
<h1 class="title">Fuzzwork Market Data</h1>
</div>
</div>
<div class="pure-g">
<div class="pure-u-1-1">
<p>Still need to write this page, and the other stuff to link off it. Probably give you historical data on the aggregates, with pretty graphs</p>
</div>
</div>
</div>
{% endblock %}
