{% extends "base.phtml" %}


{% block title %}Fuzzwork Market Data{% endblock %}

{% block content %}
<div class="content">
<div class="pure-g">
<div class="pure-u-1">
<h1 class="title">Fuzzwork Market Data</h1>
</div>
</div>
<div class="pure-g">
<div class="pure-u-1-1">
<p>Currently no API. This will change. You'll be able to request aggregates for any specific region, for a list of typeids.</p>
<p>Any further API, well, ask. I might do it.</p>
</div>
</div>
</div>
{% endblock %}
