{% extends "base.phtml" %}
{% block extrahead %}
<link href="https://cdn.datatables.net/responsive/2.2.5/css/responsive.dataTables.min.css" rel="stylesheet" type="text/css">
<script src="https://cdn.datatables.net/responsive/2.2.5/js/dataTables.responsive.min.js"></script>
<script src="/js/marketbrowser.js"></script>
<script src="/js/marketbrowser-post.js" defer></script>
<link href="/css/marketbrowser.css" rel="stylesheet" type="text/css">
{% endblock %}

{% block title %}Fuzzwork Market Data Browser{% endblock %}

{% block content %}
<div class="marketcontent">
<div class="pure-g">
    <div class="pure-u-1 pure-u-lg-1-6" id="sidebar">
        <div id="regionselectordiv">
        <select id="regionselector">
        {% for region in regions %}
        <option value="{{region.value}}" {% if region.value == 10000002 %} selected {% endif %} >{{region.label}}</option>
        {% endfor %}
        <option value=0>All Regions</option></select>
        </div>
        <div id="itemselector">
            <div id="tabbar">
            <span class="selecttab selectedtab" id="browsetab">Browse</span><span  class="selecttab" id="quickbartab">Quickbar</span>
            </div>
            <div id="searchbar">
            <input type=text id="searchbarInput" width="100%">
            </div>
            <div id="browsemenu">
            <ul id="browsemenulist" class="menulist menulisttop">
            </ul>
            </div>
        </div> 


    </div>
    <div class="pure-u-1 pure-u-lg-5-6" id="marketpane">
        <div class="pure-g">
            <div class="pure-u-3-4" id="leftdata"></div>
            <div class="pure-u-1-4" id="rightdata"></div>
        </div>
        <div id="markettabbar">
        <span class="selecttab selectedtab" id="selltab">Sell Data</span><span  class="selecttab" id="buytab">Buy Data</span>
        </div>
        <div id="marketdata">
        <table id="selldata" class="markettable" style="width:95%">
            <thead>
                <tr><th>Issued</th><th>Volume Left</th><th>Volume Entered</th><th>Minimum Volume</th><th>Price</th><th>Duration</th><th>Station Name</th><th>Region Name</th></tr>
            </thead>
        </thead>
        </table>
        <table id="buydata" class="markettable" style="width:95%">
            <thead>
                <tr><th>Issued</th><th>Volume Left</th><th>Volume Entered</th><th>Minimum Volume</th><th>Price</th><th>Range</th><th>Duration</th><th>Station Name</th><th>Region Name</th></tr>
            </thead>
        </table>
        </div>
    </div>
</div>

</div>
{% endblock %}
