{% extends "base.phtml" %}


{% block title %}Fuzzwork Market Data{% endblock %}

{% block content %}
<div class="content">
<div class="pure-g">
<div class="pure-u-1">
<h1 class="title">Fuzzwork Market Data</h1>
</div>
</div>
<div class="pure-g">
<div class="pure-u-1-1">
<p>Please select a type to see the Orders for it in the following stations</p>
<ul class="stations">
<li>Jita IV - Moon 4 - Caldari Navy Assembly Plant</li>
<li>Amarr VIII (Oris) - Emperor Family Academy</li>
<li>Dodixie IX - Moon 20 - Federation Navy Assembly Plant</li>
<li>Rens VI - Moon 8 - Brutor Tribe Treasure</li>
<li>Hek VIII - Moon 12 - Boundless Creation Factory</li>
</ul>
<input type=text id="typeid" placeholder="Select Type">
</div>
<div class="pure-u-1-1">
<ul class="minerals">
<li><a href="https://market.fuzzwork.co.uk/hub/type/34/">Tritanium</a>
<li><a href="https://market.fuzzwork.co.uk/hub/type/35/">Pyerite</a>
<li><a href="https://market.fuzzwork.co.uk/hub/type/36/">Mexallon</a>
<li><a href="https://market.fuzzwork.co.uk/hub/type/37/">Isogen</a>
<li><a href="https://market.fuzzwork.co.uk/hub/type/38/">Nocxium</a>
<li><a href="https://market.fuzzwork.co.uk/hub/type/39/">Zydrine</a>
<li><a href="https://market.fuzzwork.co.uk/hub/type/40/">Megacyte</a>
<li><a href="https://market.fuzzwork.co.uk/hub/type/11399/">Morphite</a>
</ul>
</div>
</div>
</div>
{% endblock %}
{%block footercontent %}
  <script>
  $(function() {
    $.getJSON( "/api/typeids", function( data ) {
    $( "#typeid" ).autocomplete({
      source: data,
      minLength: 2,
      select: function( event, ui ) {
        event.preventDefault();
        $( "#typeid" ).val(ui.item.label);
        window.location="https://market.fuzzwork.co.uk/hub/type/"+ui.item.value+"/"
      }
    });
  });
});
  </script>

{% endblock %}
