{% extends "base.phtml" %}


{% block title %}Fuzzwork Market Data{% endblock %}

{% block content %}
<div class="content">
<div class="pure-g">
<div class="pure-u-1">
<h1 class="title">Fuzzwork Market Data</h1>
<p align="center">Last Update (EVE): {{ fplastupdate|date("Y-m-d H:i") }}</p>
</div>
</div>
<div class="pure-g">
<div class="pure-u-1-1">
<h2>Forge Aggregates</h2>
<table class="aggregates">
<colgroup>
<col>
<col span=8 class="buyorders">
<col span=8 class="sellorders">
</colgroup>
<thead>
<tr><th></th><th colspan=7>Buy</th><th colspan=7>Sell</th></tr>
<tr><th>Type</th>
<th>Weighted Average</th><th>Max Price</th><th>Standard Deviation</th><th>Median</th><th>Total Volume</th><th>Number of Orders</th><th>5% Buy Average</th>
<th>Weighted Average</th><th>Min Price</th><th>Standard Deviation</th><th>Median</th><th>Total Volume</th><th>Number of Orders</th><th>5% Sell Average</th>
</thead>
<tbody>
</tr>
{% for aggregate in maggs %}
    <tr><td>{{types[loop.index0]}}</td>
        <td>{{aggregate['true'][0]|number_format(2, '.', ',')}}</td>
        <td>{{aggregate['true'][1]|number_format(2, '.', ',')}}</td>
        <td>{{aggregate['true'][3]|number_format(2, '.', ',')}}</td>
        <td>{{aggregate['true'][4]|number_format(2, '.', ',')}}</td>
        <td>{{aggregate['true'][5]|number_format(0, '.', ',')}}</td>
        <td>{{aggregate['true'][6]|number_format(0, '.', ',')}}</td>
        <td>{{aggregate['true'][7]|number_format(2, '.', ',')}}</td>
        <td>{{aggregate['false'][0]|number_format(2, '.', ',')}}</td>
        <td>{{aggregate['false'][2]|number_format(2, '.', ',')}}</td>
        <td>{{aggregate['false'][3]|number_format(2, '.', ',')}}</td>
        <td>{{aggregate['false'][4]|number_format(2, '.', ',')}}</td>
        <td>{{aggregate['false'][5]|number_format(0, '.', ',')}}</td>
        <td>{{aggregate['false'][6]|number_format(0, '.', ',')}}</td>
        <td>{{aggregate['false'][7]|number_format(2, '.', ',')}}</td></tr>
{% endfor %}
</tbody>
</table>
</div>
</div>
<div class="pure-g">
<div class="pure-u-1 pure-u-lg-1-2 ">
<h2>Top 10 Stations for Sell orders</h2>
<table class="stationstat"> 
<tr><th>Station</th><th>Number of Orders</th><th>Volume</th></tr>
{% for station in fpsell %}
    <tr><td class="station">{{station.stationName|escape}}</td><td class="alignright">{{station.coun}}</td><td class="alignright">{{station.vol}}</td></tr>
{% endfor %}
</table>
</div>
<div class="pure-u-1 pure-u-lg-1-2">
<h2>Top 10 Stations for Buy orders</h2>
<table class="stationstat">
<tr><th>Station</th><th>Number of Orders</th><th>Volume</th></tr>
{% for station in fpbuy %}
    <tr><td class="station">{{station.stationName|escape}}</td><td class="alignright">{{station.coun}}</td><td class="alignright">{{station.vol}}</td></tr>
{% endfor %}
</table>
</div>
</div>
</div>
{% endblock %}
