{% extends "base.phtml" %}


{% block title %}Fuzzwork Market Data{% endblock %}

{% block content %}
<div class="content">
<div class="pure-g">
<div class="pure-u-1">
<h1 class="title">Fuzzwork Market Data</h1>
</div>
</div>
<div class="pure-g">
<div class="pure-u-1-1">
<p>Please select a Station and a Type to see the Orders for it</p>
</ul>
<input type=text id="stationid" placeholder="Select Station">
<input type=text id="typeid" placeholder="Select Type">
</div>
</div>
</div>
{% endblock %}
{%block footercontent %}
  <script>
  $(function() {
    $( "#typeid" ).val('');
    $( "#stationid" ).val('');
    $.getJSON( "/api/typeids", function( data ) {
    $( "#typeid" ).autocomplete({
      source: data,
      minLength: 2,
      select: function( event, ui ) {
        event.preventDefault();
        $( "#typeid" ).val(ui.item.label);
        window.typeid=ui.item.value;
        if (window.typeid & window.stationid) {
            window.location="https://market.fuzzwork.co.uk/station/"+window.stationid+"/type/"+ui.item.value+"/"
        }
      }
    });
  });
    $.getJSON( "/api/stationids", function( data ) {
    $( "#stationid" ).autocomplete({
      source: data,
      minLength: 2,
      select: function( event, ui ) {
        event.preventDefault();
        $( "#stationid" ).val(ui.item.label);
        window.stationid=ui.item.value;
        if (window.typeid & window.stationid) {
            window.location="https://market.fuzzwork.co.uk/station/"+window.stationid+"/type/"+ui.item.value+"/"
        }
      }
    });
  });
});
  </script>

{% endblock %}
