{% extends "base.phtml" %}


{% block title %}Fuzzwork Market Data{% endblock %}

{% block content %}
<div class="content">
<div class="pure-g">
<div class="pure-u-1">
<h1 class="title">Fuzzwork Market Data</h1>
</div>
</div>
<div class="pure-g">
<div class="pure-u-1-1">
<p>Please select a type to see all the orders for it across New Eden.</p>
<input type=text id="typeid" placeholder="Select Type">
</div>
</div>
</div>
{% endblock %}
{%block footercontent %}
  <script>
  $(function() {
    $.getJSON( "/api/typeids", function( data ) {
    $( "#typeid" ).autocomplete({
      source: data,
      minLength: 2,
      select: function( event, ui ) {
        event.preventDefault();
        $( "#typeid" ).val(ui.item.label);
        window.location="https://market.fuzzwork.co.uk/type/"+ui.item.value+"/"
      }
    });
  });
});
  </script>

{% endblock %}
